"""Run a FLOPS notebook on Kaggle from the command line (VS Code terminal).

    python scripts/kaggle_run.py s1 push      # build + push; Kaggle runs it headless on GPU
    python scripts/kaggle_run.py s1 status    # queued / running / complete / error
    python scripts/kaggle_run.py s1 output    # download outputs + log to kaggle/output/s1/
    python scripts/kaggle_run.py s1 build     # only write kaggle/build/s1/ (inspect before pushing)

Sessions are defined in kaggle/sessions.yaml. The pushed notebook clones the repo
from GitHub at the CURRENT commit, so `push` refuses to run unless the working
tree is clean and HEAD is already on origin. Auth: ~/.kaggle/access_token (or
KAGGLE_API_TOKEN); never commit it.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SESSIONS_FILE = ROOT / "kaggle" / "sessions.yaml"
BUILD_DIR = ROOT / "kaggle" / "build"
OUTPUT_DIR = ROOT / "kaggle" / "output"

_CLONE_CELL = '''# Auto-generated by scripts/kaggle_run.py — repo pinned to the pushed commit
import subprocess, pathlib
REPO = pathlib.Path("/kaggle/working/FLOPS")
if not REPO.exists():
    subprocess.check_call(["git", "clone", "{repo_url}", str(REPO)])
subprocess.check_call(["git", "-C", str(REPO), "checkout", "--quiet", "{sha}"])
print("FLOPS commit:", subprocess.check_output(["git", "-C", str(REPO), "rev-parse", "HEAD"], text=True).strip())

# Kaggle saves an output only if /kaggle/working holds <= 500 items. Pack results
# into flops_results.zip after ANY failed cell (papermill stops there, so the last
# cell would never run) — s2 v2 lost a finished G2 run this way.
import sys
sys.path.insert(0, str(REPO))
from src.utils.kaggle_finalize import finalize_outputs

def _flops_finalize_on_error(result):
    if result.error_in_exec is not None or result.error_before_exec is not None:
        print("cell failed -> results packed:", finalize_outputs())

get_ipython().events.register("post_run_cell", _flops_finalize_on_error)
'''

_CLEANUP_CELL = '''# Auto-generated: pack results into one zip and drop bulky trees (500-item output limit).
from src.utils.kaggle_finalize import finalize_outputs
print("results packed:", finalize_outputs())
'''


def load_sessions(path: Path = SESSIONS_FILE) -> dict[str, Any]:
    return yaml.safe_load(Path(path).read_text(encoding="utf-8"))


def _apply_replacements(text: str, replace: dict[str, str]) -> str:
    for old, new in replace.items():
        count = text.count(old)
        if count != 1:
            raise ValueError(f"override {old!r} matched {count} times in the notebook (need exactly 1)")
        text = text.replace(old, new)
    return text


def session_owner(cfg: dict[str, Any], sid: str) -> str:
    """Kaggle account a session runs under: its own ``owner`` or the file-wide one.

    A session on another account needs that account's token in KAGGLE_API_TOKEN when it is
    pushed / queried (never stored in the repo)."""
    return str(cfg["sessions"][sid].get("owner", cfg["owner"]))


def build_session(cfg: dict[str, Any], sid: str, sha: str, build_root: Path) -> Path:
    """Write <build_root>/<sid>/{<slug>.ipynb, kernel-metadata.json}; return the folder."""
    import jupytext
    import nbformat

    sessions = cfg["sessions"]
    if sid not in sessions:
        raise KeyError(f"unknown session {sid!r}; defined: {sorted(sessions)}")
    s = sessions[sid]
    source = Path(s["notebook"])
    source = source if source.is_absolute() else ROOT / source
    text = _apply_replacements(source.read_text(encoding="utf-8"), s.get("replace", {}))

    nb = jupytext.reads(text, fmt="py:percent")
    nb.cells.insert(0, nbformat.v4.new_code_cell(_CLONE_CELL.format(repo_url=cfg["repo_url"], sha=sha)))
    nb.cells.append(nbformat.v4.new_code_cell(_CLEANUP_CELL))
    nb.metadata["kernelspec"] = {"name": "python3", "display_name": "Python 3", "language": "python"}

    out = Path(build_root) / sid
    out.mkdir(parents=True, exist_ok=True)
    code_file = f"{s['slug']}.ipynb"
    nbformat.write(nb, out / code_file)
    owner = session_owner(cfg, sid)
    meta = {
        "id": f"{owner}/{s['slug']}",
        "title": s["slug"],               # Kaggle derives the slug from the title
        "code_file": code_file,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        "machine_shape": cfg.get("machine_shape", ""),
        "dataset_sources": list(s.get("dataset_sources", cfg.get("dataset_sources", []))),
        "competition_sources": [],
        "kernel_sources": [k if "/" in k else f"{session_owner(cfg, k)}/{sessions[k]['slug']}"
                           for k in s.get("kernel_sources", [])],
        "model_sources": [],
    }
    (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return out


def extract_results(folder: Path) -> Path | None:
    """Unpack a downloaded flops_results.zip next to it; return the folder or None."""
    import zipfile

    archive = Path(folder) / "flops_results.zip"
    if not archive.exists():
        return None
    with zipfile.ZipFile(archive) as z:
        z.extractall(folder)
    return Path(folder)


def _git(*args: str) -> str:
    return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()


def _pushed_head() -> str:
    """HEAD sha, failing unless the tree is clean and HEAD is on origin."""
    # untracked files never reach Kaggle (it clones the pushed commit)
    if _git("status", "--porcelain", "--untracked-files=no"):
        sys.exit("Working tree has uncommitted changes — commit and push first "
                 "(Kaggle clones the repo from GitHub).")
    _git("fetch", "--quiet", "origin")
    sha = _git("rev-parse", "HEAD")
    if not _git("branch", "-r", "--contains", sha):
        sys.exit(f"HEAD {sha[:8]} is not on origin — run `git push` first.")
    return sha


def _kaggle(*args: str) -> int:
    return subprocess.call([sys.executable, "-m", "kaggle", *args])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("session", help="session id from kaggle/sessions.yaml (s1, s2, s3, s4a, s4b)")
    ap.add_argument("action", choices=["build", "push", "status", "output"])
    args = ap.parse_args()

    cfg = load_sessions()
    if args.session not in cfg["sessions"]:
        sys.exit(f"unknown session {args.session!r}; defined: {sorted(cfg['sessions'])}")
    kernel = f"{session_owner(cfg, args.session)}/{cfg['sessions'][args.session]['slug']}"

    if args.action in ("build", "push"):
        sha = _pushed_head() if args.action == "push" else _git("rev-parse", "HEAD")
        folder = build_session(cfg, args.session, sha, BUILD_DIR)
        print(f"built {folder} (commit {sha[:8]})")
        if args.action == "push":
            # The Kaggle CLI exits 0 even when it rejects the push (e.g. "Kernel push error:
            # Maximum weekly GPU quota of 30.00 hours reached"), so read its output too.
            res = subprocess.run([sys.executable, "-m", "kaggle", "kernels", "push", "-p", str(folder)],
                                 capture_output=True, text=True)
            out = (res.stdout or "") + (res.stderr or "")
            print(out, end="")
            code = res.returncode or (1 if "push error" in out.lower() else 0)
            if code == 0:
                print(f"\nRunning on Kaggle: https://www.kaggle.com/code/{kernel}\n"
                      f"  status: python scripts/kaggle_run.py {args.session} status\n"
                      f"  output: python scripts/kaggle_run.py {args.session} output")
            sys.exit(code)
    elif args.action == "status":
        sys.exit(_kaggle("kernels", "status", kernel))
    else:
        dest = OUTPUT_DIR / args.session
        dest.mkdir(parents=True, exist_ok=True)
        code = _kaggle("kernels", "output", kernel, "-p", str(dest))
        if extract_results(dest):
            print(f"extracted flops_results.zip into {dest}")
        sys.exit(code)


if __name__ == "__main__":
    main()
